services:
  db:
    image: mongo:8.2.2
    restart: always
    container_name: dp-events_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - dp-events_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: dp-events_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/

volumes:
  dp-events_data: